### ISSUE TITLE
Problem with installing acpuserprofile

### ISSUE THREAD

**Issue by suckratus** [adobe/flutter-acpuserprofile#8]
### Expected Behaviour
Plugin should be added properly
### Actual Behaviour
Project is not building and messaging about Gradle error. However when I am building without flutter_acpuserprofile the app is building and sending requests to adobe(and getting success response).

#### Steps to Reproduce
Steps:
add dependency in pubspec.yaml, 
add implementation app/build.gradle,
add native code to MyApp.kt file

#### Platform and Version
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.3 19D76, locale en-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.2)
 
[✓] Connected device (1 available)            

#### Sample Code that illustrates the problem

dependency in pubspec.yaml
`  flutter_acpuserprofile: ">= 1.0.0"
`
MyApplication.kt
```
...
import com.adobe.marketing.mobile.UserProfile;
import com.adobe.marketing.mobile.AdobeCallback;
import com.adobe.marketing.mobile.Analytics;
import com.adobe.marketing.mobile.Identity;
import com.adobe.marketing.mobile.InvalidInitException;
import com.adobe.marketing.mobile.Lifecycle;
import com.adobe.marketing.mobile.LoggingMode;
import com.adobe.marketing.mobile.MobileCore;
import com.adobe.marketing.mobile.MobileServices;
import com.adobe.marketing.mobile.Places;
import com.adobe.marketing.mobile.PlacesMonitor;
import com.adobe.marketing.mobile.Signal;
import com.adobe.marketing.mobile.WrapperType;
...

...
        MobileCore.setApplication(this)
        MobileCore.setLogLevel(LoggingMode.DEBUG)
        MobileCore.setWrapperType(WrapperType.FLUTTER)

            UserProfile.registerExtension()
            MobileServices.registerExtension()
            PlacesMonitor.registerExtension()
            Places.registerExtension()
            Analytics.registerExtension()
            Identity.registerExtension()
            Lifecycle.registerExtension()
            Signal.registerExtension()


            MobileCore.start {
                MobileCore.configureWithAppID("token")
            }

...
```

app/build.gradle 
```
...
    implementation 'com.adobe.marketing.mobile:mobileservices:1.+'
    implementation 'com.adobe.marketing.mobile:places-monitor:2.+'
    implementation 'com.adobe.marketing.mobile:places:1.+'
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.+'
    implementation 'com.adobe.marketing.mobile:userprofile:1.+'
...

```
#### Logs taken while reproducing problem

```
BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
`Running Gradle task 'assembleDebug'...
/Users/eugene/projects/eugene_apps/my_lawn/my-lawn/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:30: error: no suitable method found for add(FlutterACPUserProfilePlugin)
    flutterEngine.getPlugins().add(new com.adobe.marketing.mobile.flutter.FlutterACPUserProfilePlugin());
                              ^
    method PluginRegistry.add(FlutterPlugin) is not applicable
      (argument mismatch; FlutterACPUserProfilePlugin cannot be converted to FlutterPlugin)
    method PluginRegistry.add(Set<FlutterPlugin>) is not applicable
      (argument mismatch; FlutterACPUserProfilePlugin cannot be converted to Set<FlutterPlugin>)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by drkhannah** [comment]
We also get transitive dependencies error on ios when installing this package 

    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (ACPUserProfile and ACPCore)

**Comment by drkhannah** [comment]
i found the fix for [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (ACPUserProfile and ACPCore)

, tried to push a branch to this repo so i could make a PR but i don't have access

you need to add `s.static_framework = true` to your podspec

**Comment by jmdmpdev** [comment]
Hello all, is there a final solution for this issue ? how can we add .static_framework = true to your podspec ? I am trying to use flutter and I don't see the podspec.

**Comment by rymorale** [comment]
Hi @jmdmpdev,

I'll update the podspec and will make a new release with the changes.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by rymorale** [comment]
Hi @jmdmpdev,

The podspec changes have been released and are available in the latest flutter acpuserprofile: flutter_acpuserprofile: ">= 1.0.1"

Closing this issue.
